### PR TITLE
Upgrade codes

### PR DESCRIPTION
**Pull request by mattn**
* Add go.mod
* Delete vendor
* Migrate usage of APIs

### CODE REVIEW

**Comment by mattn** [comment]
Good news. Now Windows colors is enabled since upgrading packages.

before
image

after
image

**Comment by floryut** [comment]
@mattn Please note that this repository is no longer active and your PR will not be merged
Some of us have forked the repository under https://github.com/stern/stern/ with new release, features and everything is still supported, please take a look.

**Comment by mattn** [comment]
Ah, I didn't know it.

**Comment by floryut** [comment]
No problem, I created an issue https://github.com/wercker/stern/issues/148

But no maintainers are available and github doesn't allow us to do anything beside contacting maintainers so 🤷

**Pull request closed without merging**
