### PR TITLE
Update code to work with recent k8s.io/client-go

### PR DESCRIPTION
**Pull request by lestrrat**
This replaces vendor/vendor.json completely, which probably is not
the correct thing to do. The point of this PR is to show what
changes were necessary to compile stern with a recent k8s.io/client-go

---

I was debugging some problems that may possibly be related to 
the version of k8s.io/client-go that stern was using. This investigation
has not been completed yet, but I thought it would save somebody else's
time if I shared what I needed to change in order to work with a recent k8s.io/client-go

please feel free to close/create another PR if this doesn't work for you,
especially because I wiped out vendor/vendor.json to just get on with it.

### CODE REVIEW

**Comment by termie** [comment]
does this break any backwards compat with older versions of k8s?

**Comment by lestrrat** [comment]
honestly, I have not checked. I guess it has to do more with k8s' deprecation/support policy

**Comment by hatchan** [comment]
I've created another PR which used most of the changes provided by this PR, thanks for that :+1: . The other one does peg the version of the client to `v5.0.1` though: https://github.com/wercker/stern/pull/62

**Comment by hatchan** [comment]
Closing as #62 does the same

**Pull request closed without merging**
