### PR TITLE
Support tailing init containers and passing container state

### PR DESCRIPTION
**Pull request by shun0309**
The existing watch doesn't listen for init container and it only listens to container in running state. Supporting init containers and container state is useful to users. In order not to bother users passing container state every time, the flag has the default value of "running". https://github.com/wercker/stern/issues/53

### CODE REVIEW

**Comment by c-knowles** [comment]
@hatchan I wondered if one of the repo owners could take a look at this one?

**Comment by shun0309** [comment]
@akupila Would you mind taking a look as well?

**Comment by schlomo** [comment]
👍 I also need this feature

**Comment by wstrange** [comment]
Bump. This would be super useful

**Comment by c-knowles** [comment]
Any chance of a release containing this?

**Comment by prune998** [comment]
still not working in version 1.10.0 : 
```
Error opening stream to lab/cartodbd-1234-0: istio-init
: container "istio-init" in pod "cartodbd-1234-0" is waiting to start: PodInitializing
```

**Comment by JethroMV** [comment]
This functionality doesn't seem to be active by default in 1.11.0. Are there any extra steps needed to enable it?

**Pull request merged**
