### PR TITLE
Add support for the GCP and OIDC auth providers

### LINKED ISSUE #9: stern does not support gcp auth provider
`kubectl config view`

```
...
users:
- name: gke_[context redacted]
  user:
    auth-provider:
      config:
        access-token: [redacted]
        expiry: 2016-11-03T19:19:58.276983808-07:00
      name: gcp
...
```

`stern --context=gke_[context redacted] searchstring`
```
failed to create clientset: No Auth Provider found for name "gcp"
```

### PR DESCRIPTION
**Pull request by fd**
This required an upgrade to the 1.5 client.

Fixes #9

### CODE REVIEW

**Comment by akupila** [comment]
Oh, this fix involved much less than what i would have expected, nice find!

I'm unable to test this though, could you point at some resources regarding this so we can just double check things before merging this in? Other than verifying this works i'd say it's good to go. @hatchan maybe you have some thoughts?

**Comment by fd** [comment]
@akupila: 

* make a backup of your `.kubectl/config` file.
* enable access token based auth ([docs](https://cloud.google.com/container-engine/docs/iam-integration#authentication_modes))
  ```sh
  gcloud container clusters get-credentials <CLUSTER>
  gcloud auth application-default login
  ```

**Comment by hatchan** [comment]
Also unable to test this. But was wondering are all those new dependencies caused by the dependencies of the upgrade to kubernetes 1.5?

**Comment by fd** [comment]
> But was wondering are all those new dependencies caused by the dependencies of the upgrade to kubernetes 1.5?

AFAIK, yes. I upgraded with `govendor fetch ...` which should not included unused deps. Also i did not notice any unused packages in `govendor list`

**Comment by mhulscher** [comment]
Any update on this? Really looking forward to using stern with GCP.

**Comment by fd** [comment]
This version has been working great for me in the past 7days

**Comment by chrishiestand** [comment]
This works great for me and resolves the issue. Since there are no tests it's hard to say for sure this doesn't break anything but my vote is to merge :-)

**Comment by akupila** [comment]
Sorry for the delays here! Holidays and stuff.. While we haven't tested this i trust it's 👍

**Pull request merged**
