### PR TITLE
Add --selector flag that can filter the pods by label selector

### PR DESCRIPTION
**Pull request by superbrothers**
This commit adds --selector flag that can filter the pods by label selector.

- `--selector`, `-l`: Selector (label query) to filter on

/refs #25

### CODE REVIEW

**Comment by hatchan** [comment]
Would be cool if we can disable the normal pod query, when `-l` is used.

ie. 
```
stern web
stern -l app=web
```

The second line won't work currently as it requires the "pod-query"

**Comment by superbrothers** [comment]
OK, I'll rebase this PR and implement not to be able to use the pod-query if `-l` is used.

**Comment by superbrothers** [comment]
I rebased this PR and improved as you said. Please review the changes.

image

**Comment by akupila** [comment]
Could you add an example or two in the `Examples` section of the readme? This is a very useful addition, wouldn't want people to miss it ;)

Other than that LGTM!

**Comment by superbrothers** [comment]
I added examples.

**Comment by akupila** [comment]
Thanks @superbrothers ! 💯

**Pull request merged**
