### PR TITLE
Removing govendor and use modules

### PR DESCRIPTION
**Pull request by sorenmat**
This will remove the govendor dependency and use the go modules to
handle dependencies. This should make building this project much
easier

### CODE REVIEW

**Comment by chrism00ch** [comment]
someone please review and merge this, *please*

**Comment by sorenmat** [comment]
Doesn't seem like much is happening in this project, I wonder if it's dead?

**Comment by floryut** [comment]
@hatchan You there man ? 😄

**Comment by hatchan** [comment]
@floryut Sorry, I cannot merge as I no longer work for Wercker or Oracle anymore.

**Comment by jeff-knurek** [comment]
indeed, this project is no longer maintained. Not sure how I found my way here, but this is the current project if anyone else is looking: https://github.com/stern/stern

**Pull request closed without merging**
