### PR TITLE
Add dynamic completion support for --namespace and --context

### PR DESCRIPTION
**Pull request by superbrothers**
With this PR, stern supports dynamic completion for `--namespace` and `--context`. This feature depends on kubectl.
And the name of `--kube-config` is changed to `--kubeconfig` and `--kube-config` is marked deprecated due to using bash completion for kubectl.

```
$ source <(stern --completion=zsh)
$ stern --context=<tab>
--context=cluster01  --context=minikube
$ stern --namespace <tab>
default      kube-system
```

### CODE REVIEW

**Comment by akupila** [comment]
I was wondering the same thing. Looks like the `-` causes issues in the competion:
```
__kubectl_override_flags:local:2: not valid in this context: kube-config
```

The flag in kubectl is called `--kubeconfig`, definitely nice to be aligned with it. Too bad we need to break backwards compatibility but maybe we can bump the version to 2.0.0, the changes with Cobra and completion are pretty significant anyway

**Comment by akupila** [comment]
In terms of deprecating the flag in another pr: i think it's ok to do it here since it needs to be done because of the bash completion

**Comment by kokaz** [comment]
@akupila You're right! 

Regarding the deprecation it's not breaking backward compatibility as cobra docs says here: https://godoc.org/github.com/spf13/pflag#FlagSet.MarkDeprecated

> MarkDeprecated indicated that a flag is deprecated in your program. It will continue to function but will not show up in help or usage messages. Using this flag will also print the given usageMessage. 

Meaning this flag is still usable

**Comment by superbrothers** [comment]
I'm sorry. I forgot to explain why I rename `kube-config` to `kubeconfig`. The reason is that `__kubectl_override_flags` expects stern has `--kubeconfig`.
`--kube-config` is deprecated with this PR but it is not removed. We continue to be able to use `--kube-config` because it is only marked "deprecated". Therefore this change is not breaking change. `--kube-config` should be removed when releasd next major version (2.0.0).

```
$ bin/stern nginx --kube-config $HOME/.kube/config
Flag --kube-config has been deprecated, Use --kubeconfig instead.
+ nginx-2371676037-7gxgl › nginx
```

**Comment by superbrothers** [comment]
@kokaz 

> If that's the case I think deprecating this flag in another PR (based on this PR or on master can work I think) would be simpler to reference it in the changelog.

I think so too. This PR is not better. Should I close this PR? I can separate that to two PR.

**Comment by akupila** [comment]
Thanks for the update @superbrothers 

I'm happy to merge the PR as is but in case you want to make a separate PR for deprecating the flag that works as well. Up to you :)

**Comment by akupila** [comment]
Merging without squash so we'll keep the flag change separate.

Thanks again for another great PR! 🎉

**Comment by superbrothers** [comment]
Okay, I got it. Thank you for reviewing and merging :laughing:

**Pull request merged**
