### PR TITLE
Vendor client-go

### LINKED ISSUE #6: stern is not go gettable because of its dependency
You have hardcoded the version of the kubernetes dependency and it's not written how to install the dependency or which version you hardcoded. As I can see it's version 1.4.

```
[sszuecs@sandor-lab:~/go/src/github.com/wercker/stern]% go get github.com/wercker/stern             master
package k8s.io/client-go/1.4/kubernetes: cannot find package "k8s.io/client-go/1.4/kubernetes" in any of:
        /usr/share/go/src/k8s.io/client-go/1.4/kubernetes (from $GOROOT)
        /home/sszuecs/go/src/k8s.io/client-go/1.4/kubernetes (from $GOPATH)
package k8s.io/client-go/1.4/tools/clientcmd: cannot find package "k8s.io/client-go/1.4/tools/clientcmd" in any of:
        /usr/share/go/src/k8s.io/client-go/1.4/tools/clientcmd (from $GOROOT)
        /home/sszuecs/go/src/k8s.io/client-go/1.4/tools/clientcmd (from $GOPATH)
package k8s.io/client-go/1.4/kubernetes/typed/core/v1: cannot find package "k8s.io/client-go/1.4/kubernetes/typed/core/v1" in any of:
        /usr/share/go/src/k8s.io/client-go/1.4/kubernetes/typed/core/v1 (from $GOROOT)
        /home/sszuecs/go/src/k8s.io/client-go/1.4/kubernetes/typed/core/v1 (from $GOPATH)
package k8s.io/client-go/1.4/pkg/api: cannot find package "k8s.io/client-go/1.4/pkg/api" in any of:
        /usr/share/go/src/k8s.io/client-go/1.4/pkg/api (from $GOROOT)
        /home/sszuecs/go/src/k8s.io/client-go/1.4/pkg/api (from $GOPATH)
package k8s.io/client-go/1.4/pkg/api/v1: cannot find package "k8s.io/client-go/1.4/pkg/api/v1" in any of:
        /usr/share/go/src/k8s.io/client-go/1.4/pkg/api/v1 (from $GOROOT)
        /home/sszuecs/go/src/k8s.io/client-go/1.4/pkg/api/v1 (from $GOPATH)
package k8s.io/client-go/1.4/pkg/watch: cannot find package "k8s.io/client-go/1.4/pkg/watch" in any of:
        /usr/share/go/src/k8s.io/client-go/1.4/pkg/watch (from $GOROOT)
        /home/sszuecs/go/src/k8s.io/client-go/1.4/pkg/watch (from $GOPATH)
package k8s.io/client-go/1.4/rest: cannot find package "k8s.io/client-go/1.4/rest" in any of:
        /usr/share/go/src/k8s.io/client-go/1.4/rest (from $GOROOT)
        /home/sszuecs/go/src/k8s.io/client-go/1.4/rest (from $GOPATH)
zsh: exit 1     go get github.com/wercker/stern
[sszuecs@sandor-lab:~/go/src/github.com/wercker/stern]% ls -al $GOPATH/src/k8s.io/client-go/        master
total 88
drwxr-xr-x 16 sszuecs sszuecs  4096 Nov  1 09:27 ./
drwxr-xr-x  5 sszuecs sszuecs  4096 Nov  1 09:27 ../
-rw-r--r--  1 sszuecs sszuecs   222 Nov  1 09:27 CHANGELOG.md
drwxr-xr-x  3 sszuecs sszuecs  4096 Nov  1 09:27 discovery/
drwxr-xr-x  2 sszuecs sszuecs  4096 Nov  1 09:27 dynamic/
drwxr-xr-x  4 sszuecs sszuecs  4096 Nov  1 09:27 examples/
drwxr-xr-x  8 sszuecs sszuecs  4096 Nov  1 09:50 .git/
drwxr-xr-x  2 sszuecs sszuecs  4096 Nov  1 09:27 .github/
drwxr-xr-x  2 sszuecs sszuecs  4096 Nov  1 09:27 Godeps/
drwxr-xr-x  4 sszuecs sszuecs  4096 Nov  1 09:27 kubernetes/
-rw-r--r--  1 sszuecs sszuecs 11354 Nov  1 09:27 LICENSE
drwxr-xr-x 20 sszuecs sszuecs  4096 Nov  1 09:27 pkg/
drwxr-xr-x  3 sszuecs sszuecs  4096 Nov  1 09:27 plugin/
-rw-r--r--  1 sszuecs sszuecs  5435 Nov  1 09:27 README.md
drwxr-xr-x  3 sszuecs sszuecs  4096 Nov  1 09:27 rest/
drwxr-xr-x  2 sszuecs sszuecs  4096 Nov  1 09:27 testing/
drwxr-xr-x  8 sszuecs sszuecs  4096 Nov  1 09:27 tools/
drwxr-xr-x  2 sszuecs sszuecs  4096 Nov  1 09:27 transport/
drwxr-xr-x  7 sszuecs sszuecs  4096 Nov  1 09:27 vendor/
```

### PR DESCRIPTION
**Pull request by topu**
Fixes #6

### CODE REVIEW

**Comment by brockoffdev** [comment]
Can we get this merged in please? Blocker to actually using `stern`.

**Comment by etiennemarais** [comment]
Yeah please, it's blocking any installation and usage of this tool.

**Comment by akupila** [comment]
Thank you for the PR! Sorry for the late response, somehow i didn't receive any notifications for the stern repo..

This fixes the `k8s` dependency but doesn't address the other dependencies. I've updated the readme in #10, hopefully is should clear things up a bit?

**Comment by topu** [comment]
This would make stern "go gettable" without any significant code changes which are necessary if using Kubernetes `client-go` library from latest master branch. The ideal approach would be to rewrite some code to use the latest Kubernetes `client-go`.

Using external tools for vendoring causes that the app no longer can be installed by `go get`. Of course making app "go gettable" can sometimes break the app build if one of the dependencies changes in non-backward compatible way, similarly to the problem we are facing right now.

**Comment by akupila** [comment]
Vendoring will always remain a problem but with govendor we can track the exact versions and have repeatable builds. As a binary can be downloaded directly we'll stick to govendor which unfortunately removes the ability to `go get`. Updated instructions were merged in https://github.com/wercker/stern/pull/10

Thanks again for the PR, sorry that we can't merge this in

**Pull request closed without merging**
